### PR TITLE
Include and use pandoc in wheel for OS X

### PR DESCRIPTION
**Pull request by msabramo**
I copied a Homebrew-built pandoc and libgmp, using delocate to rewrite
the pandoc binary to look for the library in ../lib instead of
/usr/local/lib.

This pandoc binary and libgmp dylib get included in wheels.

If we can't find `pandoc` and `sys.platform == darwin` then we use the
darwin pandoc in the wheel.

```
$ brew uninstall pandoc libgmp
...
$ pip uninstall pypandoc; pip install ~/dev/git-repos/pypandoc/dist/pypandoc-0.9.0-py2-none-any.whl
Uninstalling pypandoc-0.9.0:
  Successfully uninstalled pypandoc-0.9.0
Processing ./dev/git-repos/pypandoc/dist/pypandoc-0.9.0-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./python/virtualenvs/pypandoc-standalone/lib/python2.7/site-packages (from pypandoc==0.9.0)
Installing collected packages: pypandoc

Successfully installed pypandoc-0.9.0

$ ipython
Python 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46)
Type "copyright", "credits" or "license" for more information.

IPython 2.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pypandoc

In [2]: pypandoc.convert('[google](http://www.google.com/)', 'rst', format='md')
Out[2]: u'`google <http://www.google.com/>`__\n'
```

### CODE REVIEW

**Comment by bebraw** [comment]
* What would you think of dropping that `PANDOC` global? 
* Can you provide binary update instructions somewhere (separate file for dev docs?)? I expect the binary needs to be updated at some point.

Thanks for your work, though.

**Comment by msabramo** [comment]
OK, I just removed the `PANDOC` global.

I should figure out how to include a **Linux** binary so that Travis CI doesn't fail. :smile:

**Comment by msabramo** [comment]
Later, I'll add some instructions for how to update the binary. Didn't forget.

**Comment by JanSchulz** [comment]
the pandoc supplied binaries are static as far as I can tell (only include pandoc and pandoc-citeproc, no libs). So that might make this much easier...

**Comment by JanSchulz** [comment]
See #73 for a different idea how to build wheels with pandoc binaries included. Only includes windows, but darwin (and linux) should be easy, I just don't have any macbook to test...

**Comment by JanSchulz** [comment]
The windows part is merged, it would be great if either you (@msabramo) or @bebraw could do the mac part, if you have a mac handy :-)

**Comment by JanSchulz** [comment]
The wheels should now include pandoc: https://pypi.python.org/pypi/pypandoc/1.1.1

Please reopen if it's not working for you... :-)

**Pull request closed without merging**
