### PR TITLE
Fix PEP 8 issues

### PR DESCRIPTION
**Pull request by msabramo**
```
$ tox -e flake8
GLOB sdist-make: /Users/marca/dev/git-repos/pypandoc/setup.py
flake8 inst-nodeps:
/Users/marca/dev/git-repos/pypandoc/.tox/dist/pypandoc-0.8.6.zip
flake8 runtests: PYTHONHASHSEED='2700628100'
flake8 runtests: commands[0] | flake8 pypandoc.py tests.py
_________________________________________________________________________________________________________________
summary
__________________________________________________________________________________________________________________
  flake8: commands succeeded
  congratulations :)
```

### CODE REVIEW

**Comment by bebraw** [comment]
Could you rebase? I merged a part of your prs and now it's conflicting (merge in order).

Again, thanks a lot!

**Comment by msabramo** [comment]
Rebased and resolved merge conflicts.

**Comment by bebraw** [comment]
Awesome. Thanks. :)

**Comment by msabramo** [comment]
You're welcome!

https://travis-ci.org/bebraw/pypandoc

Awesome!

**Comment by bebraw** [comment]
Yeah, looking very good. :)

**Pull request merged**
