### PR TITLE
[DO NOT MERGE] Travis work

### PR DESCRIPTION
**Pull request by JanSchulz**
Add python 3.5 to the test matrix. We could probably remove 3.4 or so if that's too much testing, as 3.3 and 3.5 should cover the middle...

### CODE REVIEW

**Comment by JanSchulz** [comment]
Ok, 3.5 is not yet available: https://github.com/travis-ci/travis-ci/issues/4794

**Comment by bebraw** [comment]
Alright. Feel free to merge once Travis supports it. No objections. :+1:

**Comment by JanSchulz** [comment]
Ok, I give up for now to use our own downloader... I think we should refactor the code, so that the downloader becomes part of the library (e.g `pypandoc.download_pandoc(to_path='.', url=None)` -> you can download to some specific location (`setup.py download_pandoc` would set that to `pypandoc/files`) and also update pandoc if a new release comes out) and the setup just calls it when building wheels. This would make it possible to download pandoc by the user if there was no wheel available.

**Comment by JanSchulz** [comment]
This is now solved in #92, I just committed the py35 test addition there as well.

**Pull request closed without merging**
