### PR TITLE
version bumped, README reflect change in new version

### PR DESCRIPTION
**Pull request by ickc**
This is **after** #126, and any potential changes you want to make before v1.4.

### CODE REVIEW

**Comment by janschulz** [comment]
LGTM, will merge after the other PR #128

**Comment by ickc** [comment]
Also this one?

**Comment by janschulz** [comment]
@ickc Sorry for the delay, I need to setup my dev machine and then will merge this and tag the release. The other PRs were simply merged in the github web UI...

**Comment by ickc** [comment]
You can also git tag it in releases. If you have setup Travis to deploy to PyPI, that would works for PyPI deployment too.

Anyway, take your time.

**Comment by ickc** [comment]
@janschulz, merge now?

**Comment by janschulz** [comment]
Close and reopen to check CI builds

**Comment by janschulz** [comment]
@ickc Sorry that it took so long :-(

**Comment by ickc** [comment]
No problem! After all, these are our volunteer jobs and we have the other one that consumes most of our time ;)

**Pull request merged**
